spring:
    datasource:
        url: jdbc:mysql://localhost:3306/S3Test
        username: root
        password: 1234
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    cloud:
        aws:
            credentials:
                accessKey: ${aws.access.key}
                secretKey: ${aws.secret.key}
            region:
                static: ap-northeast-2
            stack:
                auto: false
            s3:
                bucket: ${aws.s3.bucket}
                # url: ${aws.s3.bucket.url}
